#- name: restart_apache
#  ansible.builtin.service:
#    name: apache2
#    state: restarted
#    enabled: yes
#
- name: restart_apache
  ansible.builtin.systemd_service:
    state: restarted
    name: apache2
    enabled: true
    masked: no