---
- name: install nginx
  ansible.builtin.apt:
    name:
      - nginx
    state: present

- name: Arrancamos y Habilitamos en el arranque nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes