---
- name: install apache
  ansible.builtin.apt:
    name:
      - apache2
    state: present

- name: Arrancamos y Habilitamos en el arranque Apache
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes
