---
- name: install apache
  ansible.builtin.apt:
    name:
      - apache2
    state: present

- name: Forzamos la redireccion HTTPS
  ansible.builtin.template:
    src: 000-default.conf.j2
    dest: /etc/apache2/sites-enabled/000-default.conf

- name: Habilitamos el modulo rewrite
  ansible.builtin.file:
    src: /etc/apache2/mods-available/rewrite.load
    dest: /etc/apache2/mods-enabled/rewrite.load
    state: link

- name: Habilitamos el modulo socache_shmcb como dependencia de SSL
  ansible.builtin.file:
    src: /etc/apache2/mods-available/socache_shmcb.load
    dest: /etc/apache2/mods-enabled/socache_shmcb.load
    state: link

- name: Habilitamos el modulo de SSL
  ansible.builtin.file:
    src: /etc/apache2/mods-available/ssl.load
    dest: /etc/apache2/mods-enabled/ssl.load
    state: link

- name: Habilitamos la configuracion del modulo SSL
  ansible.builtin.file:
    src: /etc/apache2/mods-available/ssl.conf
    dest: /etc/apache2/mods-enabled/ssl.conf
    state: link

- name: Habilitamos el sitio por defecto HTTPS
  ansible.builtin.file:
    src: /etc/apache2/sites-available/default-ssl.conf
    dest: /etc/apache2/sites-enabled/default-ssl.conf
    state: link

  notify: restart_apache