---

- name: Homelab Configurations
  hosts: homelab
  become: yes
  become_method: sudo
  roles:
    - homelab

- name: Common Tasks
  hosts: all
  become: yes
  become_method: sudo
  roles:
    - common

- name: Instalando Wordpress (Apache + MariaDB + Php)
  hosts: lamp
  become: yes
  become_method: sudo
  roles:
    - lamp
    - wordpress

- name: Instalando Wordpress (Lighttpd + MariaDB + Php)
  hosts: llmp
  become: yes
  become_method: sudo
  roles:
    - llmp
    - wordpress

- name: Instalando Wordpress (Nginx + MariaDB + Php)
  hosts: lnmp
  become: yes
  become_method: sudo
  roles:
    - lnmp
    - wordpress