---

- name: Homelab Configurations
  hosts: all
  become: yes
  become_method: sudo
  roles:
    - homelab

- name: Common Tasks
  hosts: all
  become: yes
  become_method: sudo
  vars:
    NORMAL_USER_NAME: 'ppcojo'
    NORMAL_USER_PASS: '$6$1/g/rmFXEQeo.rBm$H5ab4JI3K5NbYyqp8PF9u9NipArTvygwbCqBrBvyU3fdxLo7K.dxHJSyowdawqmB.F.aPY28zYt0Q6RsZOCHM0'
    NORMAL_USER_PUB_KEY: '~/.ssh/mitrans_ansible_key.pub'
  roles:
    - common

- name: Dns (Bind9)
  hosts: dns
  become: yes
  become_method: sudo
  roles:
    - dns

- name: Wordpress (Apache + MariaDB + Php) version deb
  hosts: wordpress
  become: yes
  become_method: sudo
  roles:
    - wordpress