---

- name: Homelab Configurations
  hosts: all
  become: yes
  become_method: sudo
  roles:
    - homelab

- name: Common Tasks
  hosts: all
  become: yes
  become_method: sudo
  vars:
    NORMAL_USER_NAME: 'ppcojo'
    NORMAL_USER_PASS: '$6$1/g/rmFXEQeo.rBm$H5ab4JI3K5NbYyqp8PF9u9NipArTvygwbCqBrBvyU3fdxLo7K.dxHJSyowdawqmB.F.aPY28zYt0Q6RsZOCHM0'
    NORMAL_USER_PUB_KEY: '~/.ssh/mitrans_ansible_key.pub'
  roles:
    - common

- name: Instalando Wordpress (Apache + MariaDB + Php)
  hosts: wordpress_lamp
  become: yes
  become_method: sudo
  roles:
    - lamp
    - wordpress

- name: Instalando Wordpress (Lighttpd + MariaDB + Php)
  hosts: wordpress_llmp
  become: yes
  become_method: sudo
  roles:
    - llmp
    - wordpress

- name: Instalando Wordpress (Nginx + MariaDB + Php)
  hosts: wordpress_lnmp
  become: yes
  become_method: sudo
  roles:
    - lnmp
    - wordpress

- name: Instalando Correo Electronico Local
  hosts: email_local
  become: yes
  become_method: sudo
  vars:
    MAIL_NAME: 'mail'
    MAIL_DOMAIN: 'homelab.cu'
  roles:
    - email-local