---
- name: Create directory para la configuracion php del sitio
  ansible.builtin.file:
    path: /etc/nginx/sites-available/php/
    state: directory
    mode: '0755'

- name: Configuramos el site with php support
  ansible.builtin.template:
    src: php_default.j2
    dest: /etc/nginx/sites-available/php/php_default

  notify: restart_nginx