---
- name: Install MariaDB
  ansible.builtin.apt:
    name:
      - mariadb-server
    state: present

- name: Install Ansible MariaDB support
  ansible.builtin.apt:
    name:
      - python3-mysqldb
    state: present

- name: Arrancamos y Habilitamos en el arranque MariaDB
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes
