---
- name: install PHP roundcube dependencies
  ansible.builtin.apt:
    name:
      - php-intl
      - php-gd
      - php-curl
      - php-ldap
      - php-imap
      - php-mbstring
      - php-xml
      - php-zip
      - php-json
      - php-imagick
    state: present

- name: install roundcube
  ansible.builtin.apt:
    name:
      - roundcube
      - roundcube-core
      - roundcube-mysql
    state: present

- name: Publicamos roundcube
  ansible.builtin.lineinfile:
    dest: /etc/apache2/sites-available/default-ssl.conf
    regexp: "DocumentRoot /var/www/html"
    line: "        DocumentRoot /var/lib/roundcube/public_html"
    state: present

- name: Publicamos roundcube
  ansible.builtin.lineinfile:
    dest: /etc/apache2/sites-available/default-ssl.conf
    regexp: "Available loglevels"
    line: "        Include conf-available/roundcube.conf"
    state: present