---
- name: Add homelab repos hostname
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: ’^192\.168\.56\.105’
    line: 192.168.56.1 deb.debian.org security.debian.org

- name: Copy template for manage old repositories
  ansible.builtin.template:
    src: apt.conf.j2
    dest: /etc/apt/apt.conf
