#- name: restart_nginx
#  ansible.builtin.service:
#    name: nginx
#    state: restarted
#    enabled: yes

- name: restart_nginx
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    enabled: true
    masked: no