---
- name: install soporte de php-fpm para apache
  ansible.builtin.apt:
    name:
      - libapache2-mod-php
    state: present
  notify: restart_apache
  
- name: Habilitamos la config de PROXY de PHP para Apache
  ansible.builtin.file:
    src: /etc/apache2/mods-available/proxy.conf
    dest: /etc/apache2/mods-enabled/proxy.conf
    state: link
  notify: restart_apache

- name: Habilitamos el modulo de PROXY de PHP para Apache
  ansible.builtin.file:
    src: /etc/apache2/mods-available/proxy.load
    dest: /etc/apache2/mods-enabled/proxy.load
    state: link
  notify: restart_apache

- name: Habilitamos la config de setenvif de PHP para Apache
  ansible.builtin.file:
    src: /etc/apache2/mods-available/setenvif.conf
    dest: /etc/apache2/mods-enabled/setenvif.conf
    state: link
  notify: restart_apache

- name: Habilitamos el modulo de setenvif de PHP para Apache
  ansible.builtin.file:
    src: /etc/apache2/mods-available/setenvif.load
    dest: /etc/apache2/mods-enabled/setenvif.load
    state: link
  notify: restart_apache

- name: Habilitamos el modulo de PROXY-FCGI de PHP para Apache
  ansible.builtin.file:
    src: /etc/apache2/mods-available/proxy_fcgi.load
    dest: /etc/apache2/mods-enabled/proxy_fcgi.load
    state: link
  notify: restart_apache

- name: Habilitamos la config de PHP para Apache
  ansible.builtin.file:
    src: /etc/apache2/conf-available/php8.2-fpm.conf
    dest: /etc/apache2/conf-enabled/php8.2-fpm.conf
    state: link
  notify: restart_apache